locomotion_mode: standing

timing:
  cycle: 1.0
  swing: 0.4
  stance: 0.6
  horizon: 0.5
  horizon_steps: 20

model:
  gravity: -9.81

mpc:
  friction_coefficient: 0.6
  foot_half_length: 0.065
  foot_half_width: 0.01
  torsional_friction_scale: 0.0657
  normal_force_max: 700.0
  normal_force_min: 10.0
  iterations_between_solve: 10
  state_weight_diag: [80.0, 80.0, 5.0, 2.0, 2.0, 300.0, 10.0, 10.0, 5.0, 2.0, 2.0, 15.0, 1.0]
  input_weight_diag: [3.0e-4, 3.0e-4, 3.0e-4, 3.0e-4, 3.0e-4, 3.0e-4, 3.0e-4, 3.0e-4, 3.0e-4, 3.0e-4, 3.0e-4, 3.0e-4]
  # [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  # [1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6]

swing:
  natural_frequency: [795.0, 779.0, 600.0]  # [795.0, 779.0, 600.0]
  kd_diag: [25.0, 25.0, 10.0]   # [25.0, 25.0, 10.0]
  height: 0.06
  min_remaining_time: 0.001
  touchdown_target_mode: legacy_com_yaw_corrected
  foot_end_effector_source: site  # site or body_com

foot_placement:
  velocity_feedback_gain: 0.03
  placement_clamp: 0.2
  touchdown_height: -0.003
  nominal_lateral_offset: 0.0 # -0.0018375
  swing_bias: 0.0

logging:
  gait_status_interval: 50

joint_tracking:
  leg:
    # MIT humanoid order: [hip_yaw, hip_abad, hip_pitch, knee, ankle]
    kp: [70.0, 50.0, 55.0, 60.0, 1000.0]
    kd: [15.0, 10.0, 7.0, 9.0, 100.0]
  arm:
    # MIT humanoid order: [shoulder_pitch, shoulder_abad, shoulder_yaw, elbow]
    kp: [100.0, 100.0, 100.0, 100.0]
    kd: [5.0, 5.0, 5.0, 5.0]

initial_pose:
  leg_joint_offsets: [0.0, 0.0, -0.70, 0.80, -0.35]
  arm_joint_offsets: [0.0, 0.0, 0.0, -0.65]

left_swing_hold_test:
  touchdown_target_mode: body_velocity_half_stance
  # legacy_com_yaw_corrected
  # body_velocity_half_stance
